codecov:
  bot: coverage-bot
  branch: dev

comment:
  behavior: new
  require_changes: true

coverage:
  status:
    project:
      client:
        paths:
          - client/src/**/*
        threshold: null
      server:
        paths:
          - server/app/**/*
        threshold: null
  range: 70..100
  round: down
  precision: 2

parsers:
  javascript:
    enable_partials: yes
