FROM node:11 as builder

WORKDIR /build

# Less prone to changes
COPY server/package*.json server/

# Install node_modules
RUN npm i --prefix server

# More prone to changes
COPY common/ common/
COPY server/ server/

RUN npm run tsc --prefix server

FROM node as runner

WORKDIR /app

COPY server/config config
COPY server/package*.json ./

RUN npm i --prod

COPY --from=builder /build/server/out/ /app/out

EXPOSE 3000
CMD [ "node", "out/server/app/www.js"]
