#!/bin/bash

CYAN='\033[1;36m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo ${CYAN}============== Testing client ==============${NC}
yarn --cwd client coverage
yarn --cwd client lint

echo ${CYAN}============== Testing server ==============${NC}
yarn --cwd server coverage
yarn --cwd server lint

echo ${GREEN}============== SUCCESS! ==============${NC}
