export interface Mask {
    width: number,
    height: number,
    maskLayout: number[][],
}

export const SAME_PIXEL_COLOR: number = 0xFFFFFF;
export const DIFFERENT_PIXEL_COLOR: number = 0x0;

export const DIFFERENCE_MASK = {
    width: 7,
    height: 7,
    maskLayout: [
        [SAME_PIXEL_COLOR, SAME_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, SAME_PIXEL_COLOR, SAME_PIXEL_COLOR],
        [SAME_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, SAME_PIXEL_COLOR],
        [DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR],
        [DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR],
        [DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR],
        [SAME_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, SAME_PIXEL_COLOR],
        [SAME_PIXEL_COLOR, SAME_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, DIFFERENT_PIXEL_COLOR, SAME_PIXEL_COLOR, SAME_PIXEL_COLOR],
    ]
};
