export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        GameCreatorController: Symbol("GameCreatorController"),
        GameCreatorService: Symbol("GameCreatorService"),
        DataBaseController: Symbol("DataBaseController"),
        DataBaseService: Symbol("DataBaseService"),
        DifferenceEvaluatorService: Symbol("DifferenceEvaluatorService"),
        UserNameService: Symbol("UserNameService"),
        UserNameController : Symbol("UserNameController"),
        BitmapDiffController: Symbol("BitmapDiffController"),
        BitmapDiffService: Symbol("BitmapDiffService"),
        BitmapWriter: Symbol("BitmapWriter"),
        WebsocketController: Symbol("WebSocketController"),
        ImageUploadService: Symbol("ImageUploadService"),
};
