export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        GameCreatorController: Symbol("GameCreatorController"),
        GameCreatorService: Symbol("GameCreatorService"),
        DataBaseController: Symbol("DataBaseController"),
        DataBaseService: Symbol("DataBaseService"),
        DifferenceEvaluatorService: Symbol("DifferenceEvaluatorService"),
        UserNameService: Symbol("UserNameService"),
        UserNameController : Symbol("UserNameController"),
        BitmapDiffController: Symbol("BitmapDiffController"),
        BitmapDiffService: Symbol("BitmapDiffService"),
        BitmapWriter: Symbol("BitmapWriter"),
        DiffValidatorController: Symbol("DiffValidatorController"),
        DiffValidatorService: Symbol("DiffValidatorService"),
        WebsocketController: Symbol("WebSocketController"),
        ImageUploadService: Symbol("ImageUploadService"),
        FreeGameCreatorService: Symbol("FreeGameCreatorService"),
        Object3DCreatorService: Symbol("Object3DCreatorService"),
        DummyWebsocketActionService: Symbol("DummyWebsocketActionService"),
        GameRoomService: Symbol("GameWebsocketActionService"),
};
